baseURL = 'https://ttoommmmiiee.github.io/'
languageCode = 'en-us'
title = 'Tommie Introna: UAL MRes Creative Computing 2022-2023'
theme = 'archie'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4